import {test,expect} from '@playwright/test';
const control=`http://127.0.0.1:${process.env.DW_TEST_DB_PORT||54329}/__control`;
test('review permission is checked on every API call and revocation affects an open session',async({page,request,context})=>{
 await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
 await request.post(control,{data:{reset:true}});
 await page.goto('/sign-in');await page.getByRole('button',{name:'Sign in with LEARN'}).click();
 const id=(await(await request.get(control)).json()).member.id;
 const approve=`/api/admin/members/${id}/approve`, reject=`/api/admin/members/${id}/reject`;
 expect((await context.request.post(approve)).status()).toBe(403);
 await request.post(control,{data:{staffRole:'admin',member:{review_status:'pending_review'}}});
 expect((await context.request.get('/api/admin/reviewers')).status()).toBe(403);
 expect((await context.request.get('/api/admin/data-issues')).status()).toBe(403);
 expect((await context.request.post(`/api/admin/members/${id}/set-admin`,{data:{isAdmin:true}})).status()).toBe(403);
 expect((await context.request.post(`/api/admin/impersonate/${id}`)).status()).toBe(403);
 expect((await context.request.post(reject,{data:{feedback:123}})).status()).toBe(400);
 expect((await context.request.post(reject,{data:{feedback:'Please add your work.'}})).status()).toBe(200);
 expect((await context.request.post(approve)).status()).toBe(409);
 await request.post(control,{data:{member:{review_status:'pending_review'}}});
 expect((await context.request.post(approve)).status()).toBe(200);
 expect((await(await request.get(control)).json()).member.rejection_feedback).toBeNull();
 await request.post(control,{data:{staffRole:null,member:{review_status:'pending_review'}}});
 expect((await context.request.post(approve)).status()).toBe(403);
 expect((await context.request.post(reject,{data:{feedback:'No'}})).status()).toBe(403);
});

test('submission, changes, resubmission, approval and unpublishing preserve lifecycle state',async({page,request,context})=>{
 await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
 await request.post(control,{data:{reset:true,member:{onboarding_completed:false,review_status:'draft',is_approved:false}}});
 await page.goto('/sign-in');await page.getByRole('button',{name:'Sign in with LEARN'}).click();
 await expect(page).toHaveURL(/\/welcome$/);
 expect((await context.request.post('/api/profile/submit')).status()).toBe(409);
 await request.post(control,{data:{member:{onboarding_completed:true}}});
 await page.goto('/dashboard');
 await page.getByRole('button',{name:'Submit for review',exact:true}).click();
 await page.getByRole('button',{name:'Confirm submission',exact:true}).click();
 await expect(page.locator('span').filter({hasText:/^Under review$/})).toBeVisible();
 const snapshot=()=>request.get(control).then(r=>r.json());
 const {member}=await snapshot();
 const submitted=member.submitted_at;
 expect((await context.request.post('/api/profile/submit')).status()).toBe(200);
 expect((await snapshot()).member.submitted_at).toBe(submitted);
 await request.post(control,{data:{staffRole:'admin'}});
 expect((await context.request.post(`/api/admin/members/${member.id}/reject`,{data:{feedback:'Please expand your bio.'}})).status()).toBe(200);
 await request.post(control,{data:{staffRole:null}});
 await page.reload();await expect(page.getByText('Please expand your bio.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit bio'}).click();
 await page.getByRole('textbox',{name:'Bio',exact:true}).fill('I design accessible products.');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.getByRole('button',{name:'Submit for review',exact:true}).click();
 await page.getByRole('button',{name:'Confirm submission',exact:true}).click();
 await expect(page.locator('span').filter({hasText:/^Under review$/})).toBeVisible();
 await request.post(control,{data:{staffRole:'admin'}});
 expect((await context.request.post(`/api/admin/members/${member.id}/approve`)).status()).toBe(200);
 await request.post(control,{data:{staffRole:null}});
 await page.reload();
 await page.getByRole('link',{name:'View public profile ↗',exact:true}).click();
 await expect(page.getByText('I design accessible products.',{exact:true})).toBeVisible();
 await page.goto('/dashboard');
 await page.getByRole('button',{name:'Unpublish',exact:true}).click();
 await page.getByRole('button',{name:'Unpublish profile',exact:true}).click();
 await expect(page.getByRole('button',{name:'Submit for review',exact:true})).toBeVisible();
 expect((await snapshot()).member.review_status).toBe('draft');
 expect((await snapshot()).member.is_approved).toBe(false);
});
