import {test,expect} from '@playwright/test';
const CONTROL=`http://127.0.0.1:${process.env.DW_TEST_DB_PORT||54329}/__control`;
for(const width of [1440,390])test(`account workspace editing at ${width}`,async({page,request,context})=>{
 await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
 await request.post(CONTROL,{data:{reset:true}});
 await page.setViewportSize({width,height:1000});await page.goto('/sign-in');await page.getByRole('button',{name:'Sign in with LEARN'}).click();
 await expect(page.getByRole('heading',{name:'Your profile',exact:true})).toBeVisible();
 await expect(page.getByText('The person behind your work.')).toHaveCount(0);
 await page.getByRole('button',{name:'Change or crop profile photo'}).click();await expect(page.getByRole('dialog')).toBeVisible();
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=10;c.height=10;const ctx=c.getContext('2d')!;ctx.fillStyle='red';ctx.fillRect(0,0,10,10);return c.toDataURL().split(',')[1];});
 await page.getByLabel('Change photo',{exact:true}).setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await expect(page.getByRole('button',{name:'Save photo',exact:true})).toBeEnabled();
 await page.getByLabel('Zoom',{exact:true}).fill('2');
 expect(await page.locator('canvas').evaluate((c:HTMLCanvasElement)=>c.getContext('2d')!.getImageData(320,400,1,1).data[0])).toBe(255);
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.screenshot({path:`test-results/account-workspace-${width}.png`,fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Edit bio'}).click();
 await page.getByRole('textbox',{name:'Bio',exact:true}).fill('Discard this');
 await expect(page.getByRole('navigation',{name:'Account workspace'}).getByRole('button',{name:'Experience'})).toBeDisabled();
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await expect(page.getByText('Discard this')).toHaveCount(0);
 await page.getByRole('button',{name:'Edit bio'}).click();await page.getByRole('textbox',{name:'Bio',exact:true}).fill('Building useful things.');
 await request.post(CONTROL,{data:{failSave:true}});await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.locator('p[role=alert]')).toContainText('Couldn’t save');await expect(page.getByRole('textbox',{name:'Bio',exact:true})).toHaveValue('Building useful things.');
 await request.post(CONTROL,{data:{failSave:false}});await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Changes saved.');
 const saved=(await(await request.get(CONTROL)).json()).member;expect(saved.bio).toBe('Building useful things.');expect(saved.program).toBe('Computer Science');
 await page.getByRole('button',{name:'Edit program'}).click();await page.screenshot({path:`test-results/account-studies-${width}.png`,fullPage:true});await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await expect(page.getByLabel('Portfolio',{exact:true})).toBeVisible();await expect(page.getByLabel('Behance',{exact:true})).toHaveCount(0);
 await page.getByLabel('Portfolio',{exact:true}).fill('https://example.com');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Changes saved.');expect((await(await request.get(CONTROL)).json()).member.bio).toBe('Building useful things.');
 await page.getByLabel('Portfolio',{exact:true}).fill('https://discard.example.com');await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByLabel('Portfolio',{exact:true})).toHaveValue('https://example.com/');
 const nav=page.getByRole('navigation',{name:'Account workspace'});
 await nav.getByRole('button',{name:'Experience'}).click();await page.getByRole('button',{name:'Edit experience',exact:true}).click();await page.getByRole('button',{name:'+ Add position',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Designer');await page.getByLabel('Company',{exact:true}).fill('Studio');await page.getByLabel('Start year',{exact:true}).fill('2025');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Experience saved.');expect((await(await request.get(CONTROL)).json()).member.bio).toBe('Building useful things.');
 await page.getByRole('button',{name:'Edit leadership',exact:true}).click();await page.getByRole('button',{name:'+ Add leadership role',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Organizer');await page.getByLabel('Organization',{exact:true}).fill('Design Club');await page.getByLabel('Start year',{exact:true}).fill('2024');await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Experience saved.');await expect(page.getByText('Designer',{exact:true})).toBeVisible();
 await nav.getByRole('button',{name:'Availability'}).click();await expect(page.locator('button[data-term]').first()).toBeVisible();await page.getByRole('button',{name:'Edit work terms'}).click();await page.screenshot({path:`test-results/account-schedule-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await nav.getByRole('button',{name:'Account',exact:true}).click();await expect(page.getByRole('link',{name:'Replay onboarding'})).toBeVisible();await page.screenshot({path:`test-results/account-settings-${width}.png`,fullPage:true});
});
