import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const CONTROL=`http://127.0.0.1:${process.env.DW_TEST_DB_PORT||54329}/__control`;
const sample=readFileSync('tests/fixtures/linkedin-experience.txt','utf8');
for(const width of [1440,390]) test(`experience paste, edits and save at ${width}px`,async({page,request,context})=>{
 await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
 await request.post(CONTROL,{data:{reset:true,member:{onboarding_completed:true,review_status:'draft',is_approved:false}}});
 await page.setViewportSize({width,height:1000});
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto('/sign-in');await page.getByRole('button',{name:'Sign in with LEARN'}).click();
 await page.goto('/dashboard#experience');
 await page.getByRole('button',{name:'Edit experience',exact:true}).click();
 const next=page.getByRole('button',{name:'Save changes',exact:true});
 await page.emulateMedia({reducedMotion:'no-preference'});
 const box=page.getByLabel('Copy your LinkedIn Experience section');
 await box.evaluate((el,text)=>{const data=new DataTransfer();data.setData('text/plain',text);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true}));},sample);
 await expect(page.getByRole('status')).toContainText('11 positions added');
 await expect(page.locator('[class*="positions"] > li')).toHaveCount(11);
 const timing=await page.locator('[class*="positions"] > li').last().evaluate(el=>{const s=getComputedStyle(el);return parseFloat(s.animationDuration)+parseFloat(s.animationDelay)});
 expect(timing).toBeLessThan(.6);
 await box.evaluate((el,text)=>{const data=new DataTransfer();data.setData('text/plain',text);el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true}));},sample);
 await expect(page.getByRole('status')).toContainText('already here');
 await page.screenshot({path:`test-results/experience-${width}.png`,fullPage:true,animations:"disabled"});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'+ Add position',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Designer');
 await page.getByLabel('Company',{exact:true}).fill('New studio');
 await page.getByLabel('Start year',{exact:true}).fill('2026');
 await page.getByLabel('I currently work here').check();
 await page.getByRole('button',{name:'Done',exact:true}).click();
 await request.post(CONTROL,{data:{failSave:true}});await next.click();
 await expect(page.locator('p[role=alert]')).toContainText('Couldn’t save');
 await expect(page.locator('[class*="positions"] > li')).toHaveCount(12);
 await request.post(CONTROL,{data:{failSave:false}});await next.click();
 await expect(page.getByRole('status')).toContainText('Experience saved.');
 const saved=(await(await request.get(CONTROL)).json()).member.member_experiences;
 expect(saved).toHaveLength(12);expect(saved.find((p:{company:string})=>p.company==='Datacurve').description).toContain('first design hire');
 await page.getByRole('button',{name:'Edit experience',exact:true}).click();
 await expect(page.locator('[class*="positions"] > li')).toHaveCount(12);
});
test('optional HTML paste extracts roles without executing pasted markup',async({page,request,context})=>{
 await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
 await request.post(CONTROL,{data:{reset:true,member:{onboarding_completed:true,review_status:'draft',is_approved:false}}});
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/sign-in');await page.getByRole('button',{name:'Sign in with LEARN'}).click();
 await page.goto('/dashboard#experience');
 await page.getByRole('button',{name:'Edit experience',exact:true}).click();
 await page.getByRole('button',{name:'Try HTML paste (experimental)'}).click();
 const html=process.env.DW_HTML_FIXTURE?readFileSync(process.env.DW_HTML_FIXTURE,'utf8'):'<script>window.pasteExecuted=true</script><a href="https://www.linkedin.com/company/123/"><img alt="Studio logo" src="https://media.licdn.com/logo.png" onerror="window.pasteExecuted=true"></a><p>Designer</p><p>Studio · Internship</p><p>May 2025 - Aug 2025</p><p>Built things</p>';
 await page.getByLabel('Paste Experience HTML').fill(html);await page.getByRole('button',{name:'Import text'}).click();
 await expect(page.locator('[class*="positions"] > li')).toHaveCount(process.env.DW_HTML_FIXTURE?11:1);
 expect(await page.evaluate(()=>('pasteExecuted' in window))).toBe(false);
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Experience saved.');
 const saved=(await(await request.get(CONTROL)).json()).member.member_experiences;
 expect(saved[0].link).toMatch(/^https:\/\/www.linkedin.com\/company\/\d+\/$/);expect(saved[0].logo_preview).toBeUndefined();
});
