import {test,expect} from '@playwright/test';
const control=`http://127.0.0.1:${process.env.DW_TEST_DB_PORT||54329}/__control`;
test('publication changes require confirmation, preserve state on cancel and show failures',async({page,request,context})=>{
 await context.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
 await request.post(control,{data:{reset:true}});
 await page.goto('/sign-in');await page.getByRole('button',{name:'Sign in with LEARN'}).click();
 await expect(page.getByRole('heading',{name:'Your profile',exact:true})).toBeVisible();
 let calls=0;
 await page.route('**/api/profile/unpublish',r=>{calls++;return r.fulfill({status:503,json:{error:'unavailable'}});});
 await page.getByRole('button',{name:'Unpublish',exact:true}).click();
 await expect(page.getByRole('dialog')).toContainText('you’ll need to resubmit');
 await expect(page.getByRole('dialog')).toContainText('about a day');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(calls).toBe(0);
 await page.getByRole('button',{name:'Unpublish',exact:true}).click();
 await page.getByRole('button',{name:'Unpublish profile',exact:true}).click();
 await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Couldn’t unpublish');
 expect(calls).toBe(1);await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await request.post(control,{data:{member:{review_status:'draft',is_approved:false}}});await page.reload();
 await page.getByRole('button',{name:'Submit for review',exact:true}).click();
 await expect(page.getByRole('dialog')).toContainText('hand-curate students');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 expect((await(await request.get(control)).json()).member.review_status).toBe('draft');
 await page.route('**/api/profile/submit',async r=>{await request.post(control,{data:{member:{review_status:'pending_review',submitted_at:new Date().toISOString()}}});await r.fulfill({json:{success:true}});});
 await page.route('**/api/profile/notify-review',r=>r.fulfill({json:{success:true}}));
 await page.getByRole('button',{name:'Submit for review',exact:true}).click();
 await page.getByRole('button',{name:'Confirm submission',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.locator('span').filter({hasText:/^Under review$/})).toBeVisible();
});
