import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
const user='11111111-1111-4111-8111-111111111111';
async function setup(){const db=new PGlite();await db.exec(readFileSync('tests/database-fixture.sql','utf8'));await db.exec(readFileSync('supabase/migrations/20260906010000_account_lifecycle.sql','utf8'));await db.exec(`alter table auth.users add column raw_app_meta_data jsonb default '{}';create table public.username_claims(username text,member_id uuid);insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values('${user}','test@uwaterloo.ca',now(),'{}');insert into members(first_name,last_name,slug,school_email,auth_user_id,review_status,is_approved,onboarding_completed) values('Own','Student','own','test@uwaterloo.ca','${user}','draft',false,false),('Pending','Student','pending','pending@uwaterloo.ca',null,'pending_review',false,true),('Draft','Student','draft','draft@uwaterloo.ca',null,'draft',false,false),('Public','Student','public','public@uwaterloo.ca',null,'approved',true,true);insert into username_claims select slug,id from members;`);await db.exec(readFileSync('supabase/migrations/20260909010000_review_access_rls.sql','utf8'));return db;}
async function visible(db:PGlite){return (await db.query<{slug:string}>('select slug from members order by slug')).rows.map(r=>r.slug);}
async function login(db:PGlite){await db.exec(`select set_config('request.jwt.claim.sub','${user}',false),set_config('request.jwt.claim.role','authenticated',false);set role authenticated;`);}
test('anonymous sees public profiles only, students see public and their own drafts',async()=>{const db=await setup();try{await db.exec('set role anon');assert.deepEqual(await visible(db),['public']);await db.exec('reset role');await login(db);assert.deepEqual(await visible(db),['own','public']);}finally{await db.close();}});
test('review admins read pending but not other drafts; cannot write or elevate; immediate revocation',async()=>{const db=await setup();try{await db.exec(`update auth.users set raw_app_meta_data='{"design_waterloo_role":"admin"}';`);await login(db);assert.deepEqual(await visible(db),['own','pending','public']);assert.equal((await db.query("update members set is_admin=true where slug='pending' returning id")).rows.length,0);await db.exec("update members set is_admin=true,is_approved=true,review_status='approved' where slug='own'");assert.equal((await db.query<{is_admin:boolean}>("select is_admin from members where slug='own'")).rows[0].is_admin,false);assert.equal((await db.query("delete from members where slug='pending' returning id")).rows.length,0);assert.equal((await db.query<{slug:string}>("select resolve_username('pending') as slug")).rows[0].slug,'pending');await db.exec(`reset role;update auth.users set raw_app_meta_data='{}',raw_user_meta_data='{"design_waterloo_role":"admin"}';set role authenticated;`);assert.deepEqual(await visible(db),['own','public']);}finally{await db.close();}});
test('superadmins retain full record visibility',async()=>{const db=await setup();try{await db.exec("update members set is_admin=true where slug='own'");await login(db);assert.deepEqual(await visible(db),['draft','own','pending','public']);}finally{await db.close();}});
test('related records follow visibility; reviewer cannot change another member’s content',async()=>{const db=await setup();try{
 await db.exec(`insert into member_experiences(member_id,position_title,company) select id,'Designer',slug from members;insert into member_leadership(member_id,position_title,organization) select id,'Lead',slug from members;insert into works(member_id,slug,title,review_status) select id,slug,slug,'draft' from members;set role anon;`);
 assert.equal((await db.query('select * from member_experiences')).rows.length,1);
 assert.equal((await db.query('select * from member_leadership')).rows.length,1);
 assert.equal((await db.query('select * from works')).rows.length,0);
 await db.exec(`reset role;update auth.users set raw_app_meta_data='{"design_waterloo_role":"admin"}';`);await login(db);
 assert.equal((await db.query('select * from member_experiences')).rows.length,3);
 assert.deepEqual((await db.query<{slug:string}>('select slug from works order by slug')).rows.map(r=>r.slug),['own','pending']);
 assert.equal((await db.query("update member_experiences set company='Changed' where company='pending' returning id")).rows.length,0);
 assert.equal((await db.query("update works set review_status='approved' where slug='pending' returning id")).rows.length,0);
 }finally{await db.close();}});
